# Generated by Django 4.1.1 on 2023-02-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notename', models.CharField(default='', max_length=100)),
                ('pdf_file', models.FileField(default='', upload_to='pdf')),
                ('isactive', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.video_class')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
