# Generated by Django 4.1.1 on 2023-02-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0002_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('syllabus', models.TextField()),
                ('isactive', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsmainapp.login')),
            ],
            options={
                'db_table': 'syllabus',
            },
        ),
    ]
