# Generated by Django 4.1.1 on 2023-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0005_alter_course_isdemanded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='isdemanded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
