# Generated by Django 4.1.1 on 2023-01-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0016_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='videocomment',
        ),
        migrations.AlterModelTable(
            name='videocomment',
            table='videocomment',
        ),
    ]
